// Photo data generated by `npm run images` (scripts/images.mjs) from the
// folders in assets-src/photos/ (hero/, services/, gallery/<id>/).
import type { GalleryInfo } from "@/content/home";

import { basePath } from "@/config/site";

import manifest from "./photos.generated.json";

type Entry = {
  name: string;
  width: number;
  height: number;
  widths: number[];
  hash: string;
  /** Blurred preview (data URL); absent for transparent placeholders. */
  blur?: string;
  /** Gallery photos only: the text from N.json. */
  text?: string;
};

const data: {
  hero: Entry;
  services: Entry[];
  galleries: Record<string, Entry[]>;
} = manifest;

function toPhoto({ name, width, height, widths, hash, blur }: Entry) {
  const url = (w: number) => `${basePath}/images/${name}.${hash}-${w}.webp`;
  return {
    src: url(width),
    srcSet: widths.map((w) => `${url(w)} ${w}w`).join(", "),
    width,
    height,
    blur,
  };
}

export type Photo = ReturnType<typeof toPhoto>;
export type GallerySlide = Photo & { text: string; alt: string };
export type Gallery = GalleryInfo & { slides: GallerySlide[] };

export const heroPhoto = toPhoto(data.hero);

/** One photo per service, matched by order (services/1.jpg is the first). */
export function servicePhotos(count: number): Photo[] {
  if (data.services.length !== count)
    throw new Error(
      `assets-src/photos/services/ has ${data.services.length} photos for ${count} services.`,
    );
  return data.services.map(toPhoto);
}

/**
 * Attaches the photos of gallery/<id>/ to each gallery. Every gallery needs a
 * folder and every folder a gallery, so a typo fails the build.
 */
export function withPhotos(galleries: readonly GalleryInfo[]): Gallery[] {
  const ids = galleries.map((gallery) => gallery.id);
  const folders = Object.keys(data.galleries);
  const errors = [
    ...ids
      .filter((id) => !folders.includes(id))
      .map((id) => `assets-src/photos/gallery/${id}/ is missing.`),
    ...folders
      .filter((id) => !ids.includes(id))
      .map(
        (id) => `assets-src/photos/gallery/${id}/ has no gallery in home.ts.`,
      ),
  ];
  if (errors.length) throw new Error(errors.join(" "));

  return galleries.map((gallery) => ({
    ...gallery,
    slides: data.galleries[gallery.id].map((entry) => ({
      ...toPhoto(entry),
      text: entry.text ?? "",
      alt: `${gallery.title}: ${entry.text}`,
    })),
  }));
}
