// Photo data generated by `npm run images` (scripts/images.mjs) from the files
// in assets-src/photos/. The file name without extension is the photo name.
import manifest from "./photos.generated.json";

export type PhotoName = keyof typeof manifest.photos;

type Entry = {
  width: number;
  height: number;
  widths: number[];
  hash: string;
  /** Blurred preview (data URL); absent for transparent placeholders. */
  blur?: string;
};

const photos: Record<PhotoName, Entry> = manifest.photos;

export type Photo = ReturnType<typeof photo>;

export function photo(name: PhotoName) {
  const { width, height, widths, hash, blur } = photos[name];
  const url = (w: number) => `/images/${name}.${hash}-${w}.webp`;
  return {
    src: url(width),
    srcSet: widths.map((w) => `${url(w)} ${w}w`).join(", "),
    width,
    height,
    blur,
  };
}
